"""
stocktool — License Check
Generated by OpsLabs Licenses for product STOCKTOOL
Drop this file into your project root.

MODIFIED from the vendor original — two bugs fixed, everything else
left exactly as generated:

1. The before_request gate blocked *every* request, including the
   /licence-activate endpoint and the licensing page's own assets, when
   unlicensed. That's a chicken-and-egg lock: a fresh install could never
   activate itself, since the very page and endpoint needed to enter a
   key were themselves being blocked. Fixed with a short allow-list.

2. The gate was only ever registered once, at startup, based on whether
   the license was valid *at that moment* -- and once registered, it
   unconditionally 403'd every request forever, regardless of what
   validate_license() decided on later calls. In practice this meant:
   entering a correct key via /licence-activate would flip _state["valid"]
   to True, but the app stayed locked out until a full process restart
   (activation appeared to succeed, then everything kept 403ing). Fixed
   by having the gate check current state on every request instead of
   deciding once and freezing that decision.
3. LICENSE_FILE/CACHE_FILE originally used os.path.dirname(__file__) to
   locate license.txt and the cache file. That breaks under a
   PyInstaller ONEFILE build (which this project uses -- see
   build.spec's onefile=True): PyInstaller extracts every bundled
   module to a brand-new random temp folder on EVERY launch
   (%TEMP%\\MEIxxxxxx), and __file__ for a module loaded that way
   points inside that ephemeral folder, not the actual exe's location.
   The practical symptom: license.txt gets written, the exe closes for
   any reason, the next launch gets a new temp folder, and the licence
   key is gone -- "have to enter it again" on every restart, forever.
   Fixed by putting both files in %ProgramData%\\StockToolKiosk,
   matching app/__init__.py's _local_data_dir() (used for the main
   database), for the same reason.

   REVISION: LICENSE_FILE briefly lived in the user's Documents folder
   instead, on request, for visibility -- but real-world testing
   surfaced why that doesn't actually work here: this app's primary,
   real deployment is as a WINDOWS SERVICE (see installer/), and
   services run as LocalSystem by default, not as any real person's
   account. LocalSystem's "Documents" folder is a system-profile path
   nobody looks at and doesn't match the actual user's Documents at
   all -- so a licence activated while running manually (as a real
   user) would be invisible to the same app running as the service,
   and vice versa. %ProgramData% is machine-wide and reachable
   identically by both contexts, which is the actual property needed
   here; Documents only ever worked for the manual/interactive case.
"""

import os, json, threading, time, socket, requests
from datetime import datetime, timedelta

# ── Config ────────────────────────────────────────────────────────
LICENSE_SERVER  = "https://stocktool-key.opslabsystems.cloud"
PRODUCT_CODE    = "STOCKTOOL"


def _stable_data_dir():
    """Machine-wide, reachable identically whether this process is
    running as a real interactive user or as the LocalSystem-owned
    Windows service -- see the module docstring's fix #3 for why that
    property specifically (not just 'a stable folder') is what's
    needed here."""
    base = os.environ.get("PROGRAMDATA") or os.environ.get("LOCALAPPDATA") or os.path.expanduser("~")
    path = os.path.join(base, "StockToolKiosk")
    os.makedirs(path, exist_ok=True)
    return path


_DATA_DIR       = _stable_data_dir()
LICENSE_FILE    = os.path.join(_DATA_DIR, "license.txt")
HEARTBEAT_EVERY = 3600    # seconds between heartbeats
VALIDATE_TIMEOUT= 8       # seconds before giving up on server
GRACE_PERIOD    = 86400   # 24h grace if server unreachable
CACHE_FILE      = os.path.join(_DATA_DIR, ".lc_stocktool")

# Paths that must stay reachable even while unlicensed, or nobody could
# ever activate a fresh install. Prefix-matched against request.path.
# /api/status stays exempt too -- it's the health-check endpoint that
# main.py's own _wait_for_server() polls during every startup, and what
# any external monitoring/build-verify tooling should be able to hit to
# confirm the process is alive at all, independent of licensing. Gating
# it made every unlicensed (or not-yet-validated) install look "hung"
# to any of those callers even though the server was actually up and
# serving fine -- they just kept seeing 403 instead of 200 until they
# gave up waiting.
_EXEMPT_PREFIXES = ("/licence-activate", "/static/", "/favicon.ico", "/api/status")

# ── State ─────────────────────────────────────────────────────────
_state = {
    "valid": False, "checked": False, "license_key": None,
    "activation_id": None, "customer": None, "tier": None,
    "features": [], "expires_at": None, "days_left": None,
    "error": None, "last_ok": None, "server_down": False,
}
_lock = threading.Lock()

def _read_key():
    if not os.path.exists(LICENSE_FILE): return None
    try:
        for line in open(LICENSE_FILE):
            line = line.strip()
            if line and not line.startswith("#"): return line.upper()
    except: pass
    return None

def _hardware_id():
    try:
        import uuid
        mac = ':'.join(['{:02x}'.format((uuid.getnode() >> i) & 0xff)
                        for i in range(0,48,8)][::-1])
        return f"{socket.gethostname()}-{mac}"
    except: return socket.gethostname()

def _save_cache(data):
    try:
        os.makedirs(os.path.dirname(CACHE_FILE), exist_ok=True)
        json.dump({**data, "_cached_at": datetime.utcnow().isoformat()}, open(CACHE_FILE,"w"))
    except: pass

def _load_cache():
    try:
        data = json.load(open(CACHE_FILE))
        if datetime.utcnow() - datetime.fromisoformat(data["_cached_at"]) < timedelta(seconds=GRACE_PERIOD):
            return data
    except: pass
    return None

def validate_license(key=None):
    global _state
    key = key or _read_key()
    if not key:
        with _lock: _state.update({"valid":False,"checked":True,"error":"No licence key found in license.txt"})
        return False
    payload = {"license_key": key, "hardware_id": _hardware_id(), "domain": socket.gethostname()}
    try:
        data = requests.post(f"{LICENSE_SERVER}/api/validate", json=payload, timeout=VALIDATE_TIMEOUT).json()
        if data.get("valid"):
            act_id = None
            try:
                ar = requests.post(f"{LICENSE_SERVER}/api/activate",
                                   json={**payload,"hostname":socket.gethostname()}, timeout=VALIDATE_TIMEOUT).json()
                act_id = ar.get("activation_id")
            except: pass
            with _lock:
                _state.update({"valid":True,"checked":True,"license_key":key,
                               "activation_id":act_id,"customer":data.get("customer"),
                               "tier":data.get("tier_name"),"features":data.get("features",[]),
                               "expires_at":data.get("expires_at"),"days_left":data.get("days_until_expiry"),
                               "error":None,"last_ok":datetime.utcnow(),"server_down":False})
            _save_cache(data)
            print(f"[STOCKTOOL] \u2713 Valid \u2014 {data.get('customer','?')} \u00b7 {data.get('tier_name','')} \u00b7 features: {data.get('features',[])}")
            return True
        err = data.get("error","Licence invalid")
        with _lock: _state.update({"valid":False,"checked":True,"error":err})
        print(f"[STOCKTOOL] \u2717 {err}")
        return False
    except requests.exceptions.ConnectionError:
        return _grace("Cannot reach licence server")
    except requests.exceptions.Timeout:
        return _grace("Licence server timed out")
    except Exception as e:
        return _grace(str(e))

def _grace(reason):
    cache = _load_cache()
    if cache and cache.get("valid"):
        h = round((timedelta(seconds=GRACE_PERIOD)-(datetime.utcnow()-datetime.fromisoformat(cache["_cached_at"]))).total_seconds()/3600,1)
        with _lock:
            _state.update({"valid":True,"checked":True,
                           "features":cache.get("features",[]),
                           "error":f"\u26a0 Server offline \u2014 grace period ({h}h left)","server_down":True})
        return True
    with _lock: _state.update({"valid":False,"checked":True,"error":f"Server unreachable: {reason}","server_down":True})
    return False

def send_heartbeat():
    with _lock: key, act_id = _state.get("license_key"), _state.get("activation_id")
    if not key: return
    try:
        data = requests.post(f"{LICENSE_SERVER}/api/heartbeat",
                             json={"license_key":key,"activation_id":act_id}, timeout=VALIDATE_TIMEOUT).json()
        if data.get("valid"):
            with _lock: _state["last_ok"] = datetime.utcnow(); _state["server_down"] = False
    except: pass

def _heartbeat_loop():
    time.sleep(HEARTBEAT_EVERY)
    while True:
        try: send_heartbeat()
        except: pass
        time.sleep(HEARTBEAT_EVERY)

def is_valid():
    with _lock: return _state["valid"]

def get_state():
    with _lock: return dict(_state)

def has_feature(code):
    """Check if a specific feature is enabled for this licence."""
    with _lock: return code in _state.get("features", [])

def init_license(app=None):
    """Call this on startup. Pass your Flask app to block if invalid.

    validate_license() makes up to two chained network calls (/api/validate,
    then /api/activate), each with an 8s timeout -- up to ~16s. This used to
    run inline here, inside create_app(), which runs *before*
    server_supervisor.py ever calls serve() to bind the port. On a slow or
    unreachable license server that delay alone could push total startup
    past main.py's 15s _wait_for_server() budget, so the embedded server
    would still be stuck validating a license when main.py gave up waiting
    and printed a (misleading) "port already in use" error -- the port was
    never the problem, the license check just hadn't finished yet.

    Fixed by running the initial check in a background thread instead, same
    as the heartbeat loop below it. The before_request gate already re-reads
    is_valid() on every request rather than freezing a decision made once at
    startup, so there's no correctness reason validate_license() needs to
    finish before the app starts serving -- it's briefly unlicensed (which
    the gate already handles) until the background check completes, instead
    of the whole server being unreachable for that same window."""
    t = threading.Thread(target=validate_license, daemon=True, name="LicenceValidate_STOCKTOOL")
    t.start()
    hb = threading.Thread(target=_heartbeat_loop, daemon=True, name="LicenceHeartbeat_STOCKTOOL")
    hb.start()
    if app:
        @app.before_request
        def _block():
            from flask import request, render_template
            if request.path.startswith(_EXEMPT_PREFIXES):
                return None
            if is_valid():
                return None
            return render_template("license_invalid.html", error=get_state().get("error")), 403
    return None
