#!/usr/bin/env bash
# Disables PIN-gate enforcement on the Admin Panel's own web dashboard
# login. That gate was built for the wrong user base — it was meant for
# actual kiosk-terminal usage, not fleet managers logging into
# kiosksys.opslabsystems.cloud. No migration, no schema change - this
# only touches app/__init__.py's before_request hook.
#
# Run from inside /root/admin_panel.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

for req in app run.py; do
    if [ ! -e "$req" ]; then
        echo "Error: expected to find '$req' here - run this from the admin_panel repo root."
        exit 1
    fi
done

TS="$(date +%Y%m%d_%H%M%S)"
mkdir -p "backups/$TS"
cp app/__init__.py "backups/$TS/__init__.py.bak" 2>/dev/null || true
echo "==> Backed up existing file to backups/$TS/"

echo "==> Writing app/__init__.py"
base64 -d > app/__init__.py << 'INIT_PY_B64'
aW1wb3J0IG9zCmZyb20gZmxhc2sgaW1wb3J0IEZsYXNrCgpmcm9tIGNvbmZpZyBpbXBvcnQgQ29uZmlnCmZyb20gYXBwLmV4dGVuc2lvbnMgaW1wb3J0IGRiLCBtaWdyYXRlLCBsb2dpbl9tYW5hZ2VyLCBtYWlsCgoKZGVmIGNyZWF0ZV9hcHAoY29uZmlnX2NsYXNzPUNvbmZpZyk6CiAgICBhcHAgPSBGbGFzayhfX25hbWVfXykKICAgIGFwcC5jb25maWcuZnJvbV9vYmplY3QoY29uZmlnX2NsYXNzKQoKICAgIGRiLmluaXRfYXBwKGFwcCkKICAgIG1pZ3JhdGUuaW5pdF9hcHAoYXBwLCBkYikKICAgIGxvZ2luX21hbmFnZXIuaW5pdF9hcHAoYXBwKQogICAgbWFpbC5pbml0X2FwcChhcHApCgogICAgZnJvbSBhcHAubW9kZWxzIGltcG9ydCBVc2VyCgogICAgQGxvZ2luX21hbmFnZXIudXNlcl9sb2FkZXIKICAgIGRlZiBsb2FkX3VzZXIocHVibGljX2lkKToKICAgICAgICByZXR1cm4gVXNlci5xdWVyeS5maWx0ZXJfYnkocHVibGljX2lkPXB1YmxpY19pZCkuZmlyc3QoKQoKICAgIGZyb20gYXBwLmJsdWVwcmludHMuYXV0aCBpbXBvcnQgYnAgYXMgYXV0aF9icAogICAgZnJvbSBhcHAuYmx1ZXByaW50cy5jb21wYW5pZXMgaW1wb3J0IGJwIGFzIGNvbXBhbmllc19icAogICAgZnJvbSBhcHAuYmx1ZXByaW50cy5kYXNoYm9hcmQgaW1wb3J0IGJwIGFzIGRhc2hib2FyZF9icAogICAgZnJvbSBhcHAuYmx1ZXByaW50cy5pbnN0YW5jZXMgaW1wb3J0IGJwIGFzIGluc3RhbmNlc19icAogICAgZnJvbSBhcHAuYmx1ZXByaW50cy5hZ2VudF9hcGkgaW1wb3J0IGJwIGFzIGFnZW50X2FwaV9icAogICAgZnJvbSBhcHAuYmx1ZXByaW50cy5yZWxlYXNlcyBpbXBvcnQgYnAgYXMgcmVsZWFzZXNfYnAKICAgIGZyb20gYXBwLmJsdWVwcmludHMucGxhdGZvcm0gaW1wb3J0IGJwIGFzIHBsYXRmb3JtX2JwCiAgICBmcm9tIGFwcC5ibHVlcHJpbnRzLnJvbGxvdXRzIGltcG9ydCBicCBhcyByb2xsb3V0c19icAoKICAgIGFwcC5yZWdpc3Rlcl9ibHVlcHJpbnQoYXV0aF9icCkKICAgIGFwcC5yZWdpc3Rlcl9ibHVlcHJpbnQoY29tcGFuaWVzX2JwKQogICAgYXBwLnJlZ2lzdGVyX2JsdWVwcmludChkYXNoYm9hcmRfYnApCiAgICBhcHAucmVnaXN0ZXJfYmx1ZXByaW50KGluc3RhbmNlc19icCkKICAgIGFwcC5yZWdpc3Rlcl9ibHVlcHJpbnQoYWdlbnRfYXBpX2JwKQogICAgYXBwLnJlZ2lzdGVyX2JsdWVwcmludChyZWxlYXNlc19icCkKICAgIGFwcC5yZWdpc3Rlcl9ibHVlcHJpbnQocGxhdGZvcm1fYnApCiAgICBhcHAucmVnaXN0ZXJfYmx1ZXByaW50KHJvbGxvdXRzX2JwKQoKICAgICMgRW5kcG9pbnRzIGEgbG9nZ2VkLWluLWJ1dC1ub3QtUElOLWN1cnJlbnQgdXNlciBtdXN0IHN0aWxsIGJlIGFibGUgdG8KICAgICMgcmVhY2g6IHRoZSBQSU4gc2V0dXAgcGFnZSBpdHNlbGYgKG9yIHRoZSByZWRpcmVjdCBiZWxvdyB3b3VsZCBsb29wKSwKICAgICMgbG9nb3V0IChzbyBzb21lb25lIHdobyBkb2Vzbid0IHdhbnQgdG8gc2V0IGEgUElOIHJpZ2h0IG5vdyBpc24ndAogICAgIyB0cmFwcGVkKSwgYW5kIHN0YXRpYyBhc3NldHMuIEFnZW50LWZhY2luZyBlbmRwb2ludHMgYXJlIGV4ZW1wdGVkIGFzIGEKICAgICMgd2hvbGUgcHJlZml4IOKAlCB0aG9zZSBhcmUgbWFjaGluZS10by1tYWNoaW5lIChiZWFyZXItdG9rZW4gYXV0aCwgbm90CiAgICAjIGEgRmxhc2stTG9naW4gc2Vzc2lvbiksIG5ldmVyIHN1YmplY3QgdG8gYSBodW1hbiBQSU4gcG9saWN5IGF0IGFsbC4KICAgIF9QSU5fR0FURV9FWEVNUFRfRU5EUE9JTlRTID0geyJhdXRoLnBpbl9zZXR1cCIsICJhdXRoLmxvZ291dCIsICJzdGF0aWMifQoKICAgICMgRElTQUJMRUQgYXMgb2YgMjAyNi0wOS0wODogdGhpcyB3YXMgYnVpbHQgdG8gZ2F0ZSB0aGUgQWRtaW4gUGFuZWwncwogICAgIyBvd24gd2ViIGRhc2hib2FyZCBsb2dpbiAob3duZXJzL2FkbWlucy9tYW5hZ2Vycy9vcGVyYXRvcnMgbWFuYWdpbmcKICAgICMgdGhlIGZsZWV0IGF0IGtpb3Nrc3lzLm9wc2xhYnN5c3RlbXMuY2xvdWQpIOKAlCBidXQgdGhlIFBJTiByZXF1aXJlbWVudAogICAgIyB3YXMgbWVhbnQgZm9yIGFjdHVhbCBraW9zay10ZXJtaW5hbCB1c2FnZSBpbnN0ZWFkLCBhIGRpZmZlcmVudCB1c2VyCiAgICAjIGJhc2UgZW50aXJlbHkuIFRoZSBwaHlzaWNhbCBraW9zayB0ZXJtaW5hbCBhcHBsaWNhdGlvbiBkb2Vzbid0IGV4aXN0CiAgICAjIGFzIGEgYnVpbHQgcHJvamVjdCBpbiB0aGlzIHJlcG8geWV0LCBzbyB0aGVyZSdzIGN1cnJlbnRseSBub3doZXJlCiAgICAjIGNvcnJlY3QgdG8gYXR0YWNoIHRoaXMuIExlZnQgaW4gcGxhY2UgKHNjaGVtYSwgbW9kZWxzLCBhZG1pbiBVSSkgc28KICAgICMgaXQgY2FuIGJlIHBvaW50ZWQgYXQgdGhlIHJpZ2h0IGxvZ2luIGZsb3cgbGF0ZXIg4oCUIGp1c3Qgbm90IGVuZm9yY2VkCiAgICAjIGhlcmUgaW4gdGhlIG1lYW50aW1lLiBGbGlwIGJhY2sgdG8gVHJ1ZSB0byByZS1lbmFibGUgZGFzaGJvYXJkLXNpZGUKICAgICMgZW5mb3JjZW1lbnQgaWYgdGhhdCdzIGV2ZXIgYWN0dWFsbHkgd2FudGVkLgogICAgX1BJTl9HQVRFX0VOQUJMRUQgPSBGYWxzZQoKICAgIEBhcHAuYmVmb3JlX3JlcXVlc3QKICAgIGRlZiBlbmZvcmNlX3Bpbl9wb2xpY3koKToKICAgICAgICBpZiBub3QgX1BJTl9HQVRFX0VOQUJMRUQ6CiAgICAgICAgICAgIHJldHVybgogICAgICAgIGZyb20gZmxhc2sgaW1wb3J0IHJlcXVlc3QsIHJlZGlyZWN0LCB1cmxfZm9yCiAgICAgICAgZnJvbSBmbGFza19sb2dpbiBpbXBvcnQgY3VycmVudF91c2VyCgogICAgICAgIGlmIG5vdCBjdXJyZW50X3VzZXIuaXNfYXV0aGVudGljYXRlZDoKICAgICAgICAgICAgcmV0dXJuCiAgICAgICAgZW5kcG9pbnQgPSByZXF1ZXN0LmVuZHBvaW50CiAgICAgICAgaWYgZW5kcG9pbnQgaXMgTm9uZSBvciBlbmRwb2ludCBpbiBfUElOX0dBVEVfRVhFTVBUX0VORFBPSU5UUzoKICAgICAgICAgICAgcmV0dXJuCiAgICAgICAgaWYgZW5kcG9pbnQuc3RhcnRzd2l0aCgiYWdlbnRfYXBpLiIpOgogICAgICAgICAgICByZXR1cm4KICAgICAgICBpZiBjdXJyZW50X3VzZXIubmVlZHNfcGluX3NldHVwKCkgb3IgY3VycmVudF91c2VyLnBpbl9pc19leHBpcmVkKCk6CiAgICAgICAgICAgIHJldHVybiByZWRpcmVjdCh1cmxfZm9yKCJhdXRoLnBpbl9zZXR1cCIsIG5leHQ9cmVxdWVzdC51cmwpKQoKICAgIGZyb20gYXBwLmNsaSBpbXBvcnQgcmVnaXN0ZXJfY2xpCiAgICByZWdpc3Rlcl9jbGkoYXBwKQoKICAgIGltcG9ydCBvcwogICAgb3MubWFrZWRpcnMoYXBwLmNvbmZpZ1siVVBEQVRFX1BBQ0tBR0VfRElSIl0sIGV4aXN0X29rPVRydWUpCgogICAgQGFwcC5jb250ZXh0X3Byb2Nlc3NvcgogICAgZGVmIGluamVjdF9nbG9iYWxzKCk6CiAgICAgICAgcmV0dXJuIHsiY29tcGFueV9yb2xlcyI6IFsib3duZXIiLCAiYWRtaW5pc3RyYXRvciIsICJtYW5hZ2VyIiwgIm9wZXJhdG9yIl19CgogICAgQGFwcC5yb3V0ZSgiL2luc3RhbGwuc2giKQogICAgZGVmIGluc3RhbGxfc2goKToKICAgICAgICBmcm9tIGZsYXNrIGltcG9ydCBzZW5kX2Zyb21fZGlyZWN0b3J5CiAgICAgICAgcmV0dXJuIHNlbmRfZnJvbV9kaXJlY3RvcnkoCiAgICAgICAgICAgIG9zLnBhdGguam9pbihhcHAucm9vdF9wYXRoLCAic3RhdGljIiwgImluc3RhbGxlcnMiKSwgImluc3RhbGwuc2giLAogICAgICAgICAgICBtaW1ldHlwZT0idGV4dC94LXNoIiwKICAgICAgICApCgogICAgQGFwcC5yb3V0ZSgiL2luc3RhbGwucHMxIikKICAgIGRlZiBpbnN0YWxsX3BzMSgpOgogICAgICAgIGZyb20gZmxhc2sgaW1wb3J0IHNlbmRfZnJvbV9kaXJlY3RvcnkKICAgICAgICByZXR1cm4gc2VuZF9mcm9tX2RpcmVjdG9yeSgKICAgICAgICAgICAgb3MucGF0aC5qb2luKGFwcC5yb290X3BhdGgsICJzdGF0aWMiLCAiaW5zdGFsbGVycyIpLCAiaW5zdGFsbC5wczEiLAogICAgICAgICAgICBtaW1ldHlwZT0idGV4dC9wbGFpbiIsCiAgICAgICAgKQoKICAgIHJldHVybiBhcHAK
INIT_PY_B64

echo "==> Verifying"
python3 -c "import ast; ast.parse(open('app/__init__.py').read())"
echo "    syntax OK"

echo ""
echo "==> Restarting the admin panel app"
pkill -f "admin_panel/run.py" 2>/dev/null || true
fuser -k 6090/tcp 2>/dev/null || true
sleep 1
source venv/bin/activate
nohup python run.py > app.log 2>&1 &
disown
sleep 2
tail -n 15 app.log

echo ""
echo "==================================================================="
echo "PIN gate disabled. Nobody is required to set a PIN to use the"
echo "dashboard anymore - log in and confirm you land straight on your"
echo "company page, no PIN screen."
echo "==================================================================="
