"""Add notification preferences to settings

Revision ID: 4d81de4f97fc
Revises: 00fcbcc9a456
Create Date: 2026-08-11 21:57:16.927508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d81de4f97fc'
down_revision = '00fcbcc9a456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_on_new_booking', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('notify_on_cancellation', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('notify_on_cancellation')
        batch_op.drop_column('notify_on_new_booking')

    # ### end Alembic commands ###
