"""Add availability, time off, and settings tables

Revision ID: 88d3a0efc747
Revises: 9ba8c835eb27
Create Date: 2026-08-11 15:48:30.001287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d3a0efc747'
down_revision = '9ba8c835eb27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('manual_status', sa.String(length=20), nullable=True),
    sa.Column('manual_status_message', sa.String(length=255), nullable=True),
    sa.Column('manual_status_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_user_id'), ['user_id'], unique=True)

    op.create_table('time_off',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_off', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_off_user_id'), ['user_id'], unique=False)

    op.create_table('working_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day_of_week', name='uq_working_hours_user_day')
    )
    with op.batch_alter_table('working_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_working_hours_user_id'), ['user_id'], unique=False)

    op.create_table('breaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('working_hours_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['working_hours_id'], ['working_hours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('breaks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_breaks_working_hours_id'), ['working_hours_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breaks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breaks_working_hours_id'))

    op.drop_table('breaks')
    with op.batch_alter_table('working_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_working_hours_user_id'))

    op.drop_table('working_hours')
    with op.batch_alter_table('time_off', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_off_user_id'))

    op.drop_table('time_off')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_user_id'))

    op.drop_table('settings')
    # ### end Alembic commands ###
