"""add isp support requests

Revision ID: c709f4333571
Revises: cd6ab1fa54de
Create Date: 2026-08-12 22:10:31.102548

"""
from alembic import op
import sqlalchemy as sa
import app.services.crypto


# revision identifiers, used by Alembic.
revision = 'c709f4333571'
down_revision = 'cd6ab1fa54de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('isp_name', sa.String(length=200), nullable=False),
    sa.Column('problem_description', sa.Text(), nullable=False),
    sa.Column('account_number', app.services.crypto.EncryptedString(), nullable=True),
    sa.Column('customer_number', app.services.crypto.EncryptedString(), nullable=True),
    sa.Column('full_address', app.services.crypto.EncryptedString(), nullable=True),
    sa.Column('service_address', app.services.crypto.EncryptedString(), nullable=True),
    sa.Column('date_of_birth', app.services.crypto.EncryptedString(), nullable=True),
    sa.Column('last_bill_date', sa.String(length=20), nullable=True),
    sa.Column('last_bill_amount', sa.String(length=20), nullable=True),
    sa.Column('mothers_maiden_name', app.services.crypto.EncryptedString(), nullable=True),
    sa.Column('childhood_nickname', app.services.crypto.EncryptedString(), nullable=True),
    sa.Column('security_question', sa.String(length=255), nullable=True),
    sa.Column('security_answer', app.services.crypto.EncryptedString(), nullable=True),
    sa.Column('other_security_info', app.services.crypto.EncryptedString(), nullable=True),
    sa.Column('consent_authorised', sa.Boolean(), nullable=False),
    sa.Column('consent_accurate', sa.Boolean(), nullable=False),
    sa.Column('consent_purpose', sa.Boolean(), nullable=False),
    sa.Column('consent_additional_verification', sa.Boolean(), nullable=False),
    sa.Column('consent_no_password_request', sa.Boolean(), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_requests_submitted_at'), ['submitted_at'], unique=False)

    op.create_table('support_access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('support_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['support_request_id'], ['support_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_access_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_access_logs_support_request_id'), ['support_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_access_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_access_logs_support_request_id'))

    op.drop_table('support_access_logs')
    with op.batch_alter_table('support_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_requests_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_support_requests_status'))

    op.drop_table('support_requests')
    # ### end Alembic commands ###
