"""Add shared calendar maker tables

Revision ID: cd6ab1fa54de
Revises: f8d74b07842b
Create Date: 2026-08-12 20:54:38.107346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6ab1fa54de'
down_revision = 'f8d74b07842b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('share_token', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_calendars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_calendars_share_token'), ['share_token'], unique=True)

    op.create_table('calendar_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shared_calendar_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shared_calendar_id'], ['shared_calendars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shared_calendar_id', 'email', name='uq_calendar_access_email')
    )
    with op.batch_alter_table('calendar_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_access_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_access_shared_calendar_id'), ['shared_calendar_id'], unique=False)

    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shared_calendar_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shared_calendar_id'], ['shared_calendars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_shared_calendar_id'), ['shared_calendar_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_shared_calendar_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_event_date'))

    op.drop_table('calendar_events')
    with op.batch_alter_table('calendar_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_access_shared_calendar_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_access_email'))

    op.drop_table('calendar_access')
    with op.batch_alter_table('shared_calendars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_calendars_share_token'))

    op.drop_table('shared_calendars')
    # ### end Alembic commands ###
