"""Add current_task to settings

Revision ID: f8d74b07842b
Revises: 4d81de4f97fc
Create Date: 2026-08-12 20:34:35.336544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d74b07842b'
down_revision = '4d81de4f97fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_task', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('current_task')

    # ### end Alembic commands ###
