"""initial schema

Revision ID: 9fa17505f1d6
Revises: 
Create Date: 2026-08-21 19:40:38.554994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa17505f1d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('registration', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('motorcycles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('registration', sa.String(length=20), nullable=True),
    sa.Column('make', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('engine_info', sa.String(length=255), nullable=True),
    sa.Column('vin', sa.String(length=64), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('colour', sa.String(length=60), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('previous_owners', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('share_enabled', sa.Boolean(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('share_show_service', sa.Boolean(), nullable=True),
    sa.Column('share_show_mods', sa.Boolean(), nullable=True),
    sa.Column('share_show_parts', sa.Boolean(), nullable=True),
    sa.Column('share_show_accidents', sa.Boolean(), nullable=True),
    sa.Column('share_show_mot', sa.Boolean(), nullable=True),
    sa.Column('share_show_purchase_info', sa.Boolean(), nullable=True),
    sa.Column('share_show_documents', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('accidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('motorcycle_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('damage_caused', sa.Text(), nullable=True),
    sa.Column('repairs_carried_out', sa.Text(), nullable=True),
    sa.Column('repair_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('insurance_info', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('motorcycle_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_fitted', sa.Date(), nullable=True),
    sa.Column('mileage_fitted', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('part_number', sa.String(length=120), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('installation_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fitted_by', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mot_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('motorcycle_id', sa.String(length=36), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('mileage_unit', sa.String(length=10), nullable=True),
    sa.Column('test_number', sa.String(length=40), nullable=True),
    sa.Column('advisories', sa.Text(), nullable=True),
    sa.Column('failures', sa.Text(), nullable=True),
    sa.Column('raw_source', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motorcycle_photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('motorcycle_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('motorcycle_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('work_type', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('garage', sa.String(length=160), nullable=True),
    sa.Column('parts_used', sa.Text(), nullable=True),
    sa.Column('labour_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('parts_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts_not_fitted',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('motorcycle_id', sa.String(length=36), nullable=False),
    sa.Column('part_name', sa.String(length=160), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('part_number', sa.String(length=120), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('supplier', sa.String(length=160), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('fitted_as_modification_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fitted_as_modification_id'], ['modifications.id'], ),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('motorcycle_id', sa.String(length=36), nullable=False),
    sa.Column('service_record_id', sa.String(length=36), nullable=True),
    sa.Column('modification_id', sa.String(length=36), nullable=True),
    sa.Column('accident_id', sa.String(length=36), nullable=True),
    sa.Column('part_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('doc_type', sa.String(length=60), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accident_id'], ['accidents.id'], ),
    sa.ForeignKeyConstraint(['modification_id'], ['modifications.id'], ),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts_not_fitted.id'], ),
    sa.ForeignKeyConstraint(['service_record_id'], ['service_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('parts_not_fitted')
    op.drop_table('service_records')
    op.drop_table('motorcycle_photos')
    op.drop_table('mot_records')
    op.drop_table('modifications')
    op.drop_table('accidents')
    op.drop_table('motorcycles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('app_settings')
    op.drop_table('api_logs')
    # ### end Alembic commands ###
