"""add plan_entitlement, payment, webhook_event

Revision ID: 4be66ae60be7
Revises: c43dac0a2b23
Create Date: 2026-09-23 17:59:48.300468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be66ae60be7'
down_revision = 'c43dac0a2b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_event_stripe_event_id'), ['stripe_event_id'], unique=True)

    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_charge_id', sa.String(length=100), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('refunded_amount_cents', sa.Integer(), nullable=False),
    sa.Column('refund_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_stripe_charge_id'), ['stripe_charge_id'], unique=False)

    op.create_table('plan_entitlement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_entitlement')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_stripe_charge_id'))

    op.drop_table('payment')
    with op.batch_alter_table('webhook_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_event_stripe_event_id'))

    op.drop_table('webhook_event')
    # ### end Alembic commands ###
