"""add credits: company_credit_account, credit_ledger, credit_usage_rule

Revision ID: 53364313fe09
Revises: 4be66ae60be7
Create Date: 2026-09-23 18:05:59.958618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53364313fe09'
down_revision = '4be66ae60be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_credit_account',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('credit_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_event_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source_type', 'source_event_id', name='uq_credit_ledger_company_source')
    )
    op.create_table('credit_usage_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False),
    sa.Column('credits_cost', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_key')
    )
    # Named explicitly (autogenerate left these unnamed, which breaks downgrade()) —
    # these were actually added to the model in the previous revision's development but
    # never migrated until now; catching up here.
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_payment_stripe_payment_intent_id', ['stripe_payment_intent_id'])
        batch_op.create_unique_constraint('uq_payment_stripe_invoice_id', ['stripe_invoice_id'])


def downgrade():
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payment_stripe_payment_intent_id', type_='unique')
        batch_op.drop_constraint('uq_payment_stripe_invoice_id', type_='unique')

    op.drop_table('credit_usage_rule')
    op.drop_table('credit_ledger')
    op.drop_table('company_credit_account')
