"""add agent_jobs table

Revision ID: 51cb06937458
Revises: 54c5f2ad4e22
Create Date: 2026-07-11 14:07:51.769359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51cb06937458'
down_revision = '54c5f2ad4e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('collected_items_json', sa.Text(), nullable=True),
    sa.Column('agent_hostname', sa.String(length=255), nullable=True),
    sa.Column('agent_os', sa.String(length=20), nullable=True),
    sa.Column('export_id', sa.String(length=36), nullable=True),
    sa.Column('import_job_id', sa.String(length=36), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('log_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['export_id'], ['exports.id'], ),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_jobs_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_jobs_token'))

    op.drop_table('agent_jobs')
    # ### end Alembic commands ###
