"""add admin assist multi db support

Revision ID: c54b6c235d40
Revises: 31046f7c02a3
Create Date: 2026-07-12 01:13:20.804718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c54b6c235d40'
down_revision = '31046f7c02a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_agent_jobs')
    with op.batch_alter_table('agent_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('awaiting_admin_config', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('admin_access_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('configured_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('assist_note', sa.Text(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_agent_jobs_configured_by_users'), 'users', ['configured_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_agent_jobs_configured_by_users'), type_='foreignkey')
        batch_op.drop_column('assist_note')
        batch_op.drop_column('configured_by')
        batch_op.drop_column('admin_access_expires_at')
        batch_op.drop_column('awaiting_admin_config')

    op.create_table('_alembic_tmp_agent_jobs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('kind', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), nullable=False),
    sa.Column('config_json', sa.TEXT(), nullable=False),
    sa.Column('collected_items_json', sa.TEXT(), nullable=True),
    sa.Column('agent_hostname', sa.VARCHAR(length=255), nullable=True),
    sa.Column('agent_os', sa.VARCHAR(length=20), nullable=True),
    sa.Column('export_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('import_job_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('log_text', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('connected_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('progress_percent', sa.INTEGER(), nullable=True),
    sa.Column('awaiting_admin_config', sa.BOOLEAN(), nullable=False),
    sa.Column('admin_access_expires_at', sa.DATETIME(), nullable=True),
    sa.Column('configured_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('assist_note', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['configured_by'], ['users.id'], name=op.f('fk_agent_jobs_configured_by_users')),
    sa.ForeignKeyConstraint(['export_id'], ['exports.id'], ),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
