"""add share links and progress tracking

Revision ID: d473b4048cd9
Revises: 51cb06937458
Create Date: 2026-07-11 16:55:41.079653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd473b4048cd9'
down_revision = '51cb06937458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_share_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('export_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('requested_hours', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('needs_approval', sa.Boolean(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('failed_pin_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['export_id'], ['exports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_share_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_share_links_token'), ['token'], unique=True)

    with op.batch_alter_table('agent_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress_percent', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_jobs', schema=None) as batch_op:
        batch_op.drop_column('progress_percent')

    with op.batch_alter_table('export_share_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_share_links_token'))

    op.drop_table('export_share_links')
    # ### end Alembic commands ###
