-- OPS items for ox_inventory: paste these entries into ox_inventory/data/items.lua (inside the return { ... } table).
-- Generated from opslabs-phone/sql/ops_catalog.json (business.stock) and sql/ops_guides.json (tools & PPE). Weights in grams.

['ops_ap_wifi6'] = { label = "Wi-Fi 6 access point", weight = 800, stack = true, close = true, description = "OPS part · Wi-Fi 6 access point" },
['ops_battery'] = { label = "Home battery 10 kWh", weight = 8000, stack = true, close = true, description = "OPS part · Home battery 10 kWh" },
['ops_board'] = { label = "Server motherboard", weight = 2500, stack = true, close = true, description = "OPS part · Server motherboard" },
['ops_buttset'] = { label = "Lineman's butt set", weight = 1500, stack = false, close = true, description = "OPS tool · A test handset you clip onto a copper pair to hear dial tone and make test calls." },
['ops_cab_pcp'] = { label = "Street cabinet", weight = 2500, stack = true, close = true, description = "OPS part · Street cabinet" },
['ops_cam_anpr'] = { label = "ANPR camera", weight = 2500, stack = true, close = true, description = "OPS part · ANPR camera" },
['ops_cam_ip'] = { label = "IP camera (bullet/dome)", weight = 800, stack = true, close = true, description = "OPS part · IP camera (bullet/dome)" },
['ops_cam_ptz'] = { label = "PTZ speed dome", weight = 2500, stack = true, close = true, description = "OPS part · PTZ speed dome" },
['ops_cam_therm'] = { label = "Thermal camera", weight = 2500, stack = true, close = true, description = "OPS part · Thermal camera" },
['ops_cat6'] = { label = "CAT6 cable (per metre)", weight = 50, stack = true, close = true, description = "OPS part · CAT6 cable" },
['ops_cbt'] = { label = "Distribution point (CBT)", weight = 800, stack = true, close = true, description = "OPS part · Distribution point (CBT)" },
['ops_cones'] = { label = "Cones & barriers", weight = 1500, stack = false, close = true, description = "OPS tool · Keeps people and traffic away from open chambers, cabinets and ladders on the pavement." },
['ops_crimper'] = { label = "RJ45 crimper & cable tester", weight = 1500, stack = false, close = true, description = "OPS tool · Fits RJ45 plugs onto CAT6 and proves all eight cores are connected in the right order." },
['ops_cu'] = { label = "Consumer unit", weight = 800, stack = true, close = true, description = "OPS part · Consumer unit" },
['ops_cu_drop'] = { label = "Copper drop wire (per metre)", weight = 50, stack = true, close = true, description = "OPS part · Copper drop wire" },
['ops_disk'] = { label = "Server drive 7.68 TB", weight = 2500, stack = true, close = true, description = "OPS part · Server drive 7.68 TB" },
['ops_doorbell'] = { label = "Video doorbell", weight = 800, stack = true, close = true, description = "OPS part · Video doorbell" },
['ops_drill'] = { label = "Cordless drill & fixings", weight = 1500, stack = false, close = true, description = "OPS tool · Drills walls for cable entry and fixes brackets, cameras and boxes with the right plugs and screws." },
['ops_dvr'] = { label = "DVR 8ch", weight = 800, stack = true, close = true, description = "OPS part · DVR 8ch" },
['ops_esd'] = { label = "ESD wrist strap", weight = 600, stack = false, close = true, description = "OPS PPE · Grounds you so static electricity doesn't destroy server and network boards." },
['ops_ev'] = { label = "EV charger", weight = 2500, stack = true, close = true, description = "OPS part · EV charger" },
['ops_fan'] = { label = "Fan module", weight = 100, stack = true, close = true, description = "OPS part · Fan module" },
['ops_fib_drop'] = { label = "Fibre drop cable (per metre)", weight = 50, stack = true, close = true, description = "OPS part · Fibre drop cable" },
['ops_glasses'] = { label = "Safety glasses", weight = 600, stack = false, close = true, description = "OPS PPE · Protect your eyes from fibre shards, drilling dust and laser light." },
['ops_gloves'] = { label = "Insulated gloves", weight = 600, stack = false, close = true, description = "OPS PPE · Rated gloves for work near live electrical parts and for sharp metal edges." },
['ops_harness'] = { label = "Fall-arrest harness", weight = 600, stack = false, close = true, description = "OPS PPE · Clipped to a pole or anchor point, it stops a fall when you work above 2 m." },
['ops_hivis'] = { label = "Hi-vis vest & hard hat", weight = 600, stack = false, close = true, description = "OPS PPE · Makes you visible to traffic and protects your head from falling objects and low beams." },
['ops_inverter'] = { label = "Hybrid inverter", weight = 2500, stack = true, close = true, description = "OPS part · Hybrid inverter" },
['ops_labeler'] = { label = "Label printer", weight = 1500, stack = false, close = true, description = "OPS tool · Labels both ends of every cable and port so the next engineer knows what is what." },
['ops_ladder'] = { label = "Ladder", weight = 1500, stack = false, close = true, description = "OPS tool · Reaches walls, ceilings and pole steps. Place it at a 1-in-4 angle on firm ground." },
['ops_laptop'] = { label = "Engineer laptop & console cable", weight = 1500, stack = false, close = true, description = "OPS tool · Configures routers, NVRs and servers, runs speed tests and opens OPS Hub." },
['ops_lightmeter'] = { label = "Optical light meter / OTDR", weight = 1500, stack = false, close = true, description = "OPS tool · Measures how much light arrives down a fibre, and where along it a break or bad splice is." },
['ops_lockoff'] = { label = "Lock-off kit", weight = 1500, stack = false, close = true, description = "OPS tool · Padlocks and tags that stop anyone switching a circuit back on while you work on it." },
['ops_multimeter'] = { label = "Multimeter / voltage tester", weight = 1500, stack = false, close = true, description = "OPS tool · Proves a circuit is dead before you touch it, and measures voltage, continuity and resistance." },
['ops_nozzle'] = { label = "Dispenser nozzle", weight = 800, stack = true, close = true, description = "OPS part · Dispenser nozzle" },
['ops_nte'] = { label = "Master socket (NTE)", weight = 100, stack = true, close = true, description = "OPS part · Master socket (NTE)" },
['ops_nvr'] = { label = "NVR 16ch PoE", weight = 800, stack = true, close = true, description = "OPS part · NVR 16ch PoE" },
['ops_ont'] = { label = "Fibre ONT", weight = 800, stack = true, close = true, description = "OPS part · Fibre ONT" },
['ops_psu'] = { label = "Server PSU", weight = 800, stack = true, close = true, description = "OPS part · Server PSU" },
['ops_pv_panel'] = { label = "Solar panel 430 W", weight = 800, stack = true, close = true, description = "OPS part · Solar panel 430 W" },
['ops_reader'] = { label = "Access reader", weight = 800, stack = true, close = true, description = "OPS part · Access reader" },
['ops_rj45'] = { label = "RJ45 connectors", weight = 100, stack = true, close = true, description = "OPS part · RJ45 connectors" },
['ops_rtr_gw'] = { label = "OPS Gateway router", weight = 800, stack = true, close = true, description = "OPS part · OPS Gateway router" },
['ops_spade'] = { label = "Spade & draw rope", weight = 1500, stack = false, close = true, description = "OPS tool · Opens chamber lids and pulls cables through underground ducts." },
['ops_splice'] = { label = "Splice protectors", weight = 100, stack = true, close = true, description = "OPS part · Splice protectors" },
['ops_splicer'] = { label = "Fibre fusion splicer", weight = 1500, stack = false, close = true, description = "OPS tool · Melts two cleaned and cleaved fibres together into one low-loss joint." },
['ops_srv_c1'] = { label = "Halcyon C1 compute (1U)", weight = 8000, stack = true, close = true, description = "OPS part · Halcyon C1 compute (1U)" },
['ops_srv_c2'] = { label = "Halcyon C2 compute (2U)", weight = 8000, stack = true, close = true, description = "OPS part · Halcyon C2 compute (2U)" },
['ops_sw_poe8'] = { label = "PoE switch 8-port", weight = 800, stack = true, close = true, description = "OPS part · PoE switch 8-port" },
['ops_thermal'] = { label = "Thermal camera", weight = 1500, stack = false, close = true, description = "OPS tool · Shows hot spots: overloaded cables, failing fans, blocked server airflow." },
['ops_toner'] = { label = "Tone & probe kit", weight = 1500, stack = false, close = true, description = "OPS tool · Puts a tone on a copper pair or cable so you can find the same cable at the other end." },
['ops_torque'] = { label = "Torque driver", weight = 1500, stack = false, close = true, description = "OPS tool · Tightens electrical terminals and rack rails to the correct torque — not too loose, not stripped." },
['ops_trk'] = { label = "GPS tracker unit", weight = 800, stack = true, close = true, description = "OPS part · GPS tracker unit" },
['ops_trk_ant'] = { label = "GPS/LTE antenna", weight = 100, stack = true, close = true, description = "OPS part · GPS/LTE antenna" },
['ops_tw'] = { label = "Twin & earth cable (per metre)", weight = 50, stack = true, close = true, description = "OPS part · Twin & earth cable" },

-- OPS Buds (Config.Buds.Item): wireless earbuds in their case — use to put them in / take them out. Image: html/img/opsbuds_case.png
['ops_buds'] = { label = "OPS Buds", weight = 60, stack = false, close = true, description = "Wireless earbuds in their charging case. Use to put them in / take them out." },

-- OPS SafeMag (Config.SafeMag.Item): magnetic battery pack for the back of the phone. Image: html/img/ops_safemag.png
['ops_safemag'] = { label = "OPS SafeMag", weight = 110, stack = false, close = true, description = "Magnetic battery pack. Use to snap it onto the back of your phone / take it off." },
