server {
    listen 80;
    listen [::]:80;
    server_name opslabsystems.cloud;

    location ^~ /.well-known/acme-challenge/ {
        default_type "text/plain";
        root /var/www/html;
    }

    location / {
        return 302 https://web.opslabsystems.cloud$request_uri;
    }
}
