local F = dofile(H_ROOT .. '/bridge/tests/fakes.lua')

test('ox_core: charId identifier, names, active group as job', function()
    local H = boot(function(H)
        local fx = F.ox(H)
        GlobalState['group.lspd'] = { label = 'LSPD', grades = { 'Cadet', 'Officer', 'Sergeant' } }
        fx.add(1, { charId = 42, first = 'Kim', last = 'Lee', group = 'lspd', groups = { lspd = 2 }, bank = 900 })
    end)
    eq(FW.Info().framework, 'ox', 'framework')
    local p = H.call(function() return FW.Player(1) end)
    eq(p.identifier, '42', 'charId')
    eq(p.name, 'Kim Lee', 'name')
    eq(p.job.label, 'LSPD', 'group label')
    eq(p.job.grade.name, 'Officer', 'grade label (1-based grades)')
    eq(H.call(function() return FW.SourceOf('42') end), 1, 'SourceOf')
end)

test('ox_core: bank is the character account (online and offline), overdraft refused', function()
    local fx
    local H = boot(function(H) fx = F.ox(H) fx.add(1, { charId = 42, first = 'K', last = 'L', bank = 100 }) fx.account('c77', 5) fx.account('glspd', 1000) end)
    eq(H.call(function() return FW.GetMoney(1, 'bank') end), 100, 'balance')
    eq(H.call(function() return FW.RemoveMoney(1, 60, 'bank') end), true, 'pay')
    eq(fx.balance('c42'), 40, 'debited')
    eq(H.call(function() return FW.GetOfflineMoney('77', 'bank') end), 5, 'offline read')
    eq(H.call(function() return FW.AddOfflineMoney('77', 10, 'bank') end), true, 'offline add')
    eq(H.call(function() return FW.RemoveOfflineMoney('77', 100, 'bank') end), false, 'offline overdraft refused')
    eq(H.call(function() return FW.RemoveSocietyMoney('lspd', 300) end), true, 'group account')
    eq(fx.balance('glspd'), 700, 'group debited')
end)

test('ox_core: ox:playerLoaded / ox:playerLogout', function()
    local H = boot(function(H) F.ox(H) end)
    local loaded, unloaded
    FW.OnPlayerLoaded(function(src) loaded = src end)
    FW.OnPlayerUnloaded(function(src) unloaded = src end)
    H.emit('ox:playerLoaded', nil, 3, 1, 42)
    H.emit('ox:playerLogout', nil, 3, 1, 42)
    H.run()
    eq(loaded, 3, 'loaded') eq(unloaded, 3, 'unloaded')
end)
