# ISO 4217 currency reference data used to power the searchable currency
# selector. Kept as a single maintained list (per spec section 4) rather
# than scattering currency literals through the app.

CURRENCIES = [
    {"code": "GBP", "name": "British Pound", "symbol": "£", "flag": "🇬🇧"},
    {"code": "USD", "name": "US Dollar", "symbol": "$", "flag": "🇺🇸"},
    {"code": "EUR", "name": "Euro", "symbol": "€", "flag": "🇪🇺"},
    {"code": "CAD", "name": "Canadian Dollar", "symbol": "$", "flag": "🇨🇦"},
    {"code": "AUD", "name": "Australian Dollar", "symbol": "$", "flag": "🇦🇺"},
    {"code": "JPY", "name": "Japanese Yen", "symbol": "¥", "flag": "🇯🇵"},
    {"code": "CNY", "name": "Chinese Yuan", "symbol": "¥", "flag": "🇨🇳"},
    {"code": "INR", "name": "Indian Rupee", "symbol": "₹", "flag": "🇮🇳"},
    {"code": "CHF", "name": "Swiss Franc", "symbol": "CHF", "flag": "🇨🇭"},
    {"code": "NZD", "name": "New Zealand Dollar", "symbol": "$", "flag": "🇳🇿"},
    {"code": "SEK", "name": "Swedish Krona", "symbol": "kr", "flag": "🇸🇪"},
    {"code": "NOK", "name": "Norwegian Krone", "symbol": "kr", "flag": "🇳🇴"},
    {"code": "DKK", "name": "Danish Krone", "symbol": "kr", "flag": "🇩🇰"},
    {"code": "PLN", "name": "Polish Złoty", "symbol": "zł", "flag": "🇵🇱"},
    {"code": "AED", "name": "UAE Dirham", "symbol": "د.إ", "flag": "🇦🇪"},
    {"code": "SAR", "name": "Saudi Riyal", "symbol": "﷼", "flag": "🇸🇦"},
    {"code": "ZAR", "name": "South African Rand", "symbol": "R", "flag": "🇿🇦"},
    {"code": "BRL", "name": "Brazilian Real", "symbol": "R$", "flag": "🇧🇷"},
    {"code": "MXN", "name": "Mexican Peso", "symbol": "$", "flag": "🇲🇽"},
    {"code": "SGD", "name": "Singapore Dollar", "symbol": "$", "flag": "🇸🇬"},
    {"code": "HKD", "name": "Hong Kong Dollar", "symbol": "$", "flag": "🇭🇰"},
    {"code": "KRW", "name": "South Korean Won", "symbol": "₩", "flag": "🇰🇷"},
    {"code": "TRY", "name": "Turkish Lira", "symbol": "₺", "flag": "🇹🇷"},
    {"code": "RUB", "name": "Russian Ruble", "symbol": "₽", "flag": "🇷🇺"},
    {"code": "THB", "name": "Thai Baht", "symbol": "฿", "flag": "🇹🇭"},
    {"code": "IDR", "name": "Indonesian Rupiah", "symbol": "Rp", "flag": "🇮🇩"},
    {"code": "MYR", "name": "Malaysian Ringgit", "symbol": "RM", "flag": "🇲🇾"},
    {"code": "PHP", "name": "Philippine Peso", "symbol": "₱", "flag": "🇵🇭"},
    {"code": "VND", "name": "Vietnamese Dong", "symbol": "₫", "flag": "🇻🇳"},
    {"code": "ILS", "name": "Israeli New Shekel", "symbol": "₪", "flag": "🇮🇱"},
    {"code": "EGP", "name": "Egyptian Pound", "symbol": "£", "flag": "🇪🇬"},
    {"code": "NGN", "name": "Nigerian Naira", "symbol": "₦", "flag": "🇳🇬"},
    {"code": "KES", "name": "Kenyan Shilling", "symbol": "KSh", "flag": "🇰🇪"},
    {"code": "GHS", "name": "Ghanaian Cedi", "symbol": "₵", "flag": "🇬🇭"},
    {"code": "PKR", "name": "Pakistani Rupee", "symbol": "₨", "flag": "🇵🇰"},
    {"code": "BDT", "name": "Bangladeshi Taka", "symbol": "৳", "flag": "🇧🇩"},
    {"code": "LKR", "name": "Sri Lankan Rupee", "symbol": "₨", "flag": "🇱🇰"},
    {"code": "QAR", "name": "Qatari Riyal", "symbol": "﷼", "flag": "🇶🇦"},
    {"code": "KWD", "name": "Kuwaiti Dinar", "symbol": "د.ك", "flag": "🇰🇼"},
    {"code": "BHD", "name": "Bahraini Dinar", "symbol": ".د.ب", "flag": "🇧🇭"},
    {"code": "OMR", "name": "Omani Rial", "symbol": "﷼", "flag": "🇴🇲"},
    {"code": "JOD", "name": "Jordanian Dinar", "symbol": "د.ا", "flag": "🇯🇴"},
    {"code": "CZK", "name": "Czech Koruna", "symbol": "Kč", "flag": "🇨🇿"},
    {"code": "HUF", "name": "Hungarian Forint", "symbol": "Ft", "flag": "🇭🇺"},
    {"code": "RON", "name": "Romanian Leu", "symbol": "lei", "flag": "🇷🇴"},
    {"code": "ISK", "name": "Icelandic Króna", "symbol": "kr", "flag": "🇮🇸"},
    {"code": "UAH", "name": "Ukrainian Hryvnia", "symbol": "₴", "flag": "🇺🇦"},
    {"code": "ARS", "name": "Argentine Peso", "symbol": "$", "flag": "🇦🇷"},
    {"code": "CLP", "name": "Chilean Peso", "symbol": "$", "flag": "🇨🇱"},
    {"code": "COP", "name": "Colombian Peso", "symbol": "$", "flag": "🇨🇴"},
    {"code": "PEN", "name": "Peruvian Sol", "symbol": "S/", "flag": "🇵🇪"},
    {"code": "TWD", "name": "New Taiwan Dollar", "symbol": "$", "flag": "🇹🇼"},
    {"code": "TZS", "name": "Tanzanian Shilling", "symbol": "TSh", "flag": "🇹🇿"},
    {"code": "MAD", "name": "Moroccan Dirham", "symbol": "د.م.", "flag": "🇲🇦"},
    {"code": "DZD", "name": "Algerian Dinar", "symbol": "د.ج", "flag": "🇩🇿"},
    {"code": "IQD", "name": "Iraqi Dinar", "symbol": "ع.د", "flag": "🇮🇶"},
    {"code": "XOF", "name": "West African CFA Franc", "symbol": "CFA", "flag": "🌍"},
    {"code": "XAF", "name": "Central African CFA Franc", "symbol": "FCFA", "flag": "🌍"},
]

# Simple lookups keyed by ISO code, e.g. for validating stored contract currencies.
CURRENCY_BY_CODE = {c["code"]: c for c in CURRENCIES}


def get_currency(code):
    return CURRENCY_BY_CODE.get((code or "").upper())
