-- OPS items for ESX (es_extended items table). Run once on your database.
-- Generated from opslabs-phone/sql/ops_catalog.json and sql/ops_guides.json. Weight is in kg for ESX legacy weight systems.

INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_ap_wifi6', 'Wi-Fi 6 access point', 0.8, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_battery', 'Home battery 10 kWh', 8.0, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_board', 'Server motherboard', 2.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_buttset', 'Lineman''s butt set', 1.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_cab_pcp', 'Street cabinet', 2.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_cam_anpr', 'ANPR camera', 2.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_cam_ip', 'IP camera (bullet/dome)', 0.8, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_cam_ptz', 'PTZ speed dome', 2.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_cam_therm', 'Thermal camera', 2.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_cat6', 'CAT6 cable (per metre)', 0.05, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_cbt', 'Distribution point (CBT)', 0.8, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_cones', 'Cones & barriers', 1.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_crimper', 'RJ45 crimper & cable tester', 1.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_cu', 'Consumer unit', 0.8, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_cu_drop', 'Copper drop wire (per metre)', 0.05, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_disk', 'Server drive 7.68 TB', 2.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_doorbell', 'Video doorbell', 0.8, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_drill', 'Cordless drill & fixings', 1.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_dvr', 'DVR 8ch', 0.8, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_esd', 'ESD wrist strap', 0.6, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_ev', 'EV charger', 2.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_fan', 'Fan module', 0.1, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_fib_drop', 'Fibre drop cable (per metre)', 0.05, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_glasses', 'Safety glasses', 0.6, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_gloves', 'Insulated gloves', 0.6, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_harness', 'Fall-arrest harness', 0.6, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_hivis', 'Hi-vis vest & hard hat', 0.6, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_inverter', 'Hybrid inverter', 2.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_labeler', 'Label printer', 1.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_ladder', 'Ladder', 1.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_laptop', 'Engineer laptop & console cable', 1.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_lightmeter', 'Optical light meter / OTDR', 1.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_lockoff', 'Lock-off kit', 1.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_multimeter', 'Multimeter / voltage tester', 1.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_nozzle', 'Dispenser nozzle', 0.8, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_nte', 'Master socket (NTE)', 0.1, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_nvr', 'NVR 16ch PoE', 0.8, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_ont', 'Fibre ONT', 0.8, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_psu', 'Server PSU', 0.8, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_pv_panel', 'Solar panel 430 W', 0.8, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_reader', 'Access reader', 0.8, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_rj45', 'RJ45 connectors', 0.1, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_rtr_gw', 'OPS Gateway router', 0.8, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_spade', 'Spade & draw rope', 1.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_splice', 'Splice protectors', 0.1, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_splicer', 'Fibre fusion splicer', 1.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_srv_c1', 'Halcyon C1 compute (1U)', 8.0, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_srv_c2', 'Halcyon C2 compute (2U)', 8.0, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_sw_poe8', 'PoE switch 8-port', 0.8, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_thermal', 'Thermal camera', 1.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_toner', 'Tone & probe kit', 1.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_torque', 'Torque driver', 1.5, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_trk', 'GPS tracker unit', 0.8, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_trk_ant', 'GPS/LTE antenna', 0.1, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_tw', 'Twin & earth cable (per metre)', 0.05, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_buds', 'OPS Buds', 0.06, 0, 1);
INSERT IGNORE INTO items (name, label, weight, rare, can_remove) VALUES ('ops_safemag', 'OPS SafeMag', 0.11, 0, 1);
