"""Templates for the four files injected into every protected script, per
the spec's Automatic API Injector: license.lua, api.lua, updater.lua,
loader.lua. Placeholders are filled in per-product at build time.
"""

API_LUA = """\
-- platform/api.lua
-- Auto-generated by {site_name}. Do not edit by hand - re-upload your
-- script and this file is regenerated with fresh credentials.

CloudPlatform = CloudPlatform or {{}}
CloudPlatform.ApiBase = "{api_base}"
CloudPlatform.ProductId = "{product_id}"
CloudPlatform.ApiKey = "{api_key}"

local function buildUrl(path)
    return CloudPlatform.ApiBase .. path
end

--- POSTs JSON to the platform API.
--- @param path string endpoint path, e.g. "/api/license/activate/{product_id}"
--- @param body table request body, JSON-encoded
--- @param callback function(success: boolean, status: number, data: table)
function CloudPlatform.Post(path, body, callback)
    PerformHttpRequest(buildUrl(path), function(statusCode, responseText, headers)
        local ok, data = pcall(json.decode, responseText or "{{}}")
        if not ok then data = {{}} end
        callback(statusCode == 200, statusCode, data or {{}})
    end, "POST", json.encode(body or {{}}), {{
        ["Content-Type"] = "application/json"
    }})
end
"""

LICENSE_LUA = """\
-- platform/license.lua
-- License validation + basic security checks (Automatic API Injector).

local resourceName = GetCurrentResourceName()
CloudPlatform.LicenseValid = false

local function getLicenseKey()
    local key = GetConvar(resourceName .. "_license_key", "")
    if key == "" then
        key = GetConvar("cloudplatform_license_key", "")
    end
    return key
end

local function stopIfInvalid(reason)
    print(("^1[%s] License check failed: %s^0"):format(resourceName, reason))
    print(("^1[%s] Set a valid key: setr %s_license_key \\"YOUR-LICENSE-KEY\\" in server.cfg^0"):format(resourceName, resourceName))
    CreateThread(function()
        Wait(3000)
        StopResource(resourceName)
    end)
end

CreateThread(function()
    local licenseKey = getLicenseKey()

    if licenseKey == "" then
        stopIfInvalid("no license key configured")
        return
    end

    CloudPlatform.Post("/api/license/activate/{product_id}", {{
        api_key = CloudPlatform.ApiKey,
        license_key = licenseKey,
        server_id = GetConvar("sv_hostname", resourceName),
    }}, function(success, status, data)
        if success and data.valid then
            CloudPlatform.LicenseValid = true
            print(("^2[%s] License valid - product: %s^0"):format(resourceName, (data.product and data.product.name) or "{product_id}"))
        else
            stopIfInvalid((data and data.message) or ("HTTP " .. tostring(status)))
        end
    end)
end)

-- Re-check periodically so a revoked license takes effect without a restart.
CreateThread(function()
    while true do
        Wait(30 * 60 * 1000)
        if CloudPlatform.LicenseValid then
            CloudPlatform.Post("/api/license/activate/{product_id}", {{
                api_key = CloudPlatform.ApiKey,
                license_key = getLicenseKey(),
                server_id = GetConvar("sv_hostname", resourceName),
            }}, function(success, status, data)
                if not (success and data.valid) then
                    stopIfInvalid("license no longer valid on re-check")
                end
            end)
        end
    end
end)
"""

UPDATER_LUA = """\
-- platform/updater.lua
-- Update checker. Notifies the console if a newer version is published;
-- actual download/replacement is handled by CloudLoader (later phase).

CreateThread(function()
    Wait(5000)
    while true do
        CloudPlatform.Post("/api/update/check/{product_id}", {{
            api_key = CloudPlatform.ApiKey,
            current_version = "{product_version}",
        }}, function(success, status, data)
            if success and data.update_available then
                print(("^3[%s] Update available: {product_version} -> %s. Download it from your dashboard.^0")
                    :format(GetCurrentResourceName(), data.latest_version))
            end
        end)
        Wait(6 * 60 * 60 * 1000)
    end
end)
"""

LOADER_LUA = """\
-- platform/loader.lua
-- Auto-generated entry point / config loader. Loaded last so it can
-- confirm the other platform files initialized correctly.

print(("[%s] {site_name} protection active - product {product_id}"):format(GetCurrentResourceName()))
"""


def render_platform_files(site_name: str, api_base: str, product_id: str, api_key: str, product_version: str):
    """Returns a dict of {relative_path: content} for the platform/ folder."""
    ctx = dict(
        site_name=site_name,
        api_base=api_base,
        product_id=product_id,
        api_key=api_key,
        product_version=product_version,
    )
    return {
        "platform/api.lua": API_LUA.format(**ctx),
        "platform/license.lua": LICENSE_LUA.format(**ctx),
        "platform/updater.lua": UPDATER_LUA.format(**ctx),
        "platform/loader.lua": LOADER_LUA.format(**ctx),
    }


FXMANIFEST_INJECTION = """

-- Injected by {site_name} - do not remove, this is what makes your
-- license, updates, and API connection work.
server_script 'platform/api.lua'
server_script 'platform/license.lua'
server_script 'platform/updater.lua'
server_script 'platform/loader.lua'
"""
