"""Phase 9: infrastructure — datacenters, racks, power/network assignments

Revision ID: 3376f8f7bd1f
Revises: f3491199dcc9
Create Date: 2026-09-10 19:57:39.762757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3376f8f7bd1f'
down_revision = 'f3491199dcc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datacenters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('racks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datacenter_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('row', sa.String(length=50), nullable=True),
    sa.Column('total_u', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['datacenter_id'], ['datacenters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_item_id', sa.Integer(), nullable=False),
    sa.Column('switch_name', sa.String(length=100), nullable=True),
    sa.Column('switch_port', sa.String(length=50), nullable=True),
    sa.Column('vlan', sa.String(length=50), nullable=True),
    sa.Column('management_ip', sa.String(length=45), nullable=True),
    sa.Column('public_ipv4', sa.String(length=45), nullable=True),
    sa.Column('public_ipv6', sa.String(length=100), nullable=True),
    sa.Column('bandwidth_mbps', sa.Integer(), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_item_id'], ['customer_equipment_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_item_id', name='uq_network_assignment_item')
    )
    op.create_table('power_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_item_id', sa.Integer(), nullable=False),
    sa.Column('power_feed_a', sa.String(length=50), nullable=True),
    sa.Column('power_feed_b', sa.String(length=50), nullable=True),
    sa.Column('pdu_outlet_a', sa.String(length=50), nullable=True),
    sa.Column('pdu_outlet_b', sa.String(length=50), nullable=True),
    sa.Column('amperage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_item_id'], ['customer_equipment_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_item_id', name='uq_power_assignment_item')
    )
    op.create_table('rack_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_item_id', sa.Integer(), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=False),
    sa.Column('start_u', sa.Integer(), nullable=False),
    sa.Column('u_height', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_item_id'], ['customer_equipment_items.id'], ),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_item_id', name='uq_rack_assignment_item')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rack_assignments')
    op.drop_table('power_assignments')
    op.drop_table('network_assignments')
    op.drop_table('racks')
    op.drop_table('datacenters')
    # ### end Alembic commands ###
