"""Phase 3: marketplace — servers, categories, locations, components, images, favourites

Revision ID: 3f3202a992ba
Revises: 68397bf31bb6
Create Date: 2026-09-10 19:05:29.386086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3202a992ba'
down_revision = '68397bf31bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('asset_number', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cpu_summary', sa.String(length=255), nullable=True),
    sa.Column('cpu_count', sa.Integer(), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('cpu_threads', sa.Integer(), nullable=True),
    sa.Column('ram_summary', sa.String(length=255), nullable=True),
    sa.Column('ram_capacity_gb', sa.Integer(), nullable=True),
    sa.Column('ram_slots', sa.Integer(), nullable=True),
    sa.Column('storage_summary', sa.String(length=255), nullable=True),
    sa.Column('storage_type', sa.String(length=50), nullable=True),
    sa.Column('storage_capacity_gb', sa.Integer(), nullable=True),
    sa.Column('drive_count', sa.Integer(), nullable=True),
    sa.Column('gpu_summary', sa.String(length=255), nullable=True),
    sa.Column('gpu_count', sa.Integer(), nullable=True),
    sa.Column('network_summary', sa.String(length=255), nullable=True),
    sa.Column('network_ports', sa.Integer(), nullable=True),
    sa.Column('bandwidth_mbps', sa.Integer(), nullable=True),
    sa.Column('ip_addresses_included', sa.Integer(), nullable=True),
    sa.Column('raid_summary', sa.String(length=255), nullable=True),
    sa.Column('psu_count', sa.Integer(), nullable=True),
    sa.Column('psu_wattage', sa.Integer(), nullable=True),
    sa.Column('chassis_summary', sa.String(length=255), nullable=True),
    sa.Column('rack_units', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('one_time_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('setup_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'DISABLED', name='server_status'), nullable=False),
    sa.Column('inventory_status', sa.Enum('AVAILABLE', 'RESERVED', 'SOLD', 'MAINTENANCE', 'PROVISIONING', 'OFFLINE', 'UNAVAILABLE', name='inventory_status'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servers_slug'), ['slug'], unique=True)

    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'server_id', name='uq_favourite_user_server')
    )
    op.create_table('server_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.Enum('CPU', 'RAM', 'STORAGE', 'GPU', 'NETWORK_CARD', 'RAID_CONTROLLER', 'POWER_SUPPLY', 'CHASSIS', name='component_type'), nullable=False),
    sa.Column('hardware_id', sa.Integer(), nullable=False),
    sa.Column('label_override', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_inventory_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('AVAILABLE', 'RESERVED', 'SOLD', 'MAINTENANCE', 'PROVISIONING', 'OFFLINE', 'UNAVAILABLE', name='inventory_status_old'), nullable=True),
    sa.Column('new_status', sa.Enum('AVAILABLE', 'RESERVED', 'SOLD', 'MAINTENANCE', 'PROVISIONING', 'OFFLINE', 'UNAVAILABLE', name='inventory_status_new'), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('datacenter_name', sa.String(length=150), nullable=True),
    sa.Column('datacenter_code', sa.String(length=20), nullable=True),
    sa.Column('rack', sa.String(length=50), nullable=True),
    sa.Column('row', sa.String(length=50), nullable=True),
    sa.Column('rack_unit', sa.String(length=20), nullable=True),
    sa.Column('power_feed', sa.String(length=50), nullable=True),
    sa.Column('network_provider', sa.String(length=100), nullable=True),
    sa.Column('vlan', sa.String(length=50), nullable=True),
    sa.Column('switch_name', sa.String(length=100), nullable=True),
    sa.Column('switch_port', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_locations')
    op.drop_table('server_inventory_events')
    op.drop_table('server_images')
    op.drop_table('server_components')
    op.drop_table('favourites')
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_slug'))

    op.drop_table('servers')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))

    op.drop_table('categories')
    # ### end Alembic commands ###
