"""Phase 5: orders, cart, checkout

Revision ID: 5b55eef4e655
Revises: 9de4572a7fbf
Create Date: 2026-09-10 19:25:10.412033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b55eef4e655'
down_revision = '9de4572a7fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('setup_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AWAITING_PAYMENT', 'PAID', 'PROCESSING', 'PROVISIONING', 'READY', 'SHIPPED', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='order_status'), nullable=False),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PAID', 'PARTIALLY_PAID', 'REFUNDED', name='order_payment_status'), nullable=False),
    sa.Column('fulfilment_status', sa.Enum('PENDING', 'PROCESSING', 'PROVISIONING', 'READY', 'SHIPPED', 'COMPLETED', name='order_fulfilment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('SERVER', 'CONFIGURATION', name='cart_item_type'), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('configuration_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['server_configurations.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('SERVER', 'CONFIGURATION', name='order_item_type'), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('configuration_id', sa.Integer(), nullable=True),
    sa.Column('title_snapshot', sa.String(length=255), nullable=False),
    sa.Column('specs_snapshot', sa.JSON(), nullable=True),
    sa.Column('unit_monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_setup_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['server_configurations.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('PENDING', 'AWAITING_PAYMENT', 'PAID', 'PROCESSING', 'PROVISIONING', 'READY', 'SHIPPED', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='order_status_old'), nullable=True),
    sa.Column('new_status', sa.Enum('PENDING', 'AWAITING_PAYMENT', 'PAID', 'PROCESSING', 'PROVISIONING', 'READY', 'SHIPPED', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='order_status_new'), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_status_history')
    op.drop_table('order_items')
    op.drop_table('cart_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
