"""Phase 2: hardware catalog (CPUs, RAM, storage, GPUs, networking equipment)

Revision ID: 68397bf31bb6
Revises: aa60e1c9dce8
Create Date: 2026-09-10 18:55:46.939702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68397bf31bb6'
down_revision = 'aa60e1c9dce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware_brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('hardware_brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hardware_brands_slug'), ['slug'], unique=True)

    op.create_table('cpus',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('generation', sa.String(length=50), nullable=True),
    sa.Column('socket', sa.String(length=50), nullable=True),
    sa.Column('architecture', sa.String(length=50), nullable=True),
    sa.Column('cores', sa.Integer(), nullable=True),
    sa.Column('threads', sa.Integer(), nullable=True),
    sa.Column('base_clock_ghz', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('boost_clock_ghz', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('tdp_watts', sa.Integer(), nullable=True),
    sa.Column('cache_mb', sa.Integer(), nullable=True),
    sa.Column('pcie_generation', sa.String(length=10), nullable=True),
    sa.Column('memory_support', sa.JSON(), nullable=True),
    sa.Column('ecc_support', sa.Boolean(), nullable=True),
    sa.Column('integrated_graphics', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability', sa.Enum('IN_STOCK', 'LIMITED', 'OUT_OF_STOCK', 'DISCONTINUED', name='hw_availability'), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('external_provider_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['hardware_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cpus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cpus_external_provider_id'), ['external_provider_id'], unique=False)

    op.create_table('firewalls',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('throughput_gbps', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('port_count', sa.Integer(), nullable=True),
    sa.Column('port_type', sa.String(length=50), nullable=True),
    sa.Column('port_speed_gbps', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('interface', sa.String(length=50), nullable=True),
    sa.Column('power_requirements', sa.String(length=100), nullable=True),
    sa.Column('rack_units', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability', sa.Enum('IN_STOCK', 'LIMITED', 'OUT_OF_STOCK', 'DISCONTINUED', name='hw_availability'), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('external_provider_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['hardware_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('firewalls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firewalls_external_provider_id'), ['external_provider_id'], unique=False)

    op.create_table('gpus',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('architecture', sa.String(length=50), nullable=True),
    sa.Column('vram_gb', sa.Integer(), nullable=True),
    sa.Column('gpu_cores', sa.Integer(), nullable=True),
    sa.Column('power_watts', sa.Integer(), nullable=True),
    sa.Column('pcie_generation', sa.String(length=10), nullable=True),
    sa.Column('length_mm', sa.Integer(), nullable=True),
    sa.Column('width_mm', sa.Integer(), nullable=True),
    sa.Column('height_mm', sa.Integer(), nullable=True),
    sa.Column('cooling_type', sa.String(length=50), nullable=True),
    sa.Column('server_compatibility', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability', sa.Enum('IN_STOCK', 'LIMITED', 'OUT_OF_STOCK', 'DISCONTINUED', name='hw_availability'), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('external_provider_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['hardware_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gpus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gpus_external_provider_id'), ['external_provider_id'], unique=False)

    op.create_table('network_cards',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('port_count', sa.Integer(), nullable=True),
    sa.Column('port_type', sa.String(length=50), nullable=True),
    sa.Column('port_speed_gbps', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('interface', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability', sa.Enum('IN_STOCK', 'LIMITED', 'OUT_OF_STOCK', 'DISCONTINUED', name='hw_availability'), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('external_provider_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['hardware_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_cards_external_provider_id'), ['external_provider_id'], unique=False)

    op.create_table('network_switches',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('managed', sa.Boolean(), nullable=True),
    sa.Column('port_count', sa.Integer(), nullable=True),
    sa.Column('port_type', sa.String(length=50), nullable=True),
    sa.Column('port_speed_gbps', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('interface', sa.String(length=50), nullable=True),
    sa.Column('power_requirements', sa.String(length=100), nullable=True),
    sa.Column('rack_units', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability', sa.Enum('IN_STOCK', 'LIMITED', 'OUT_OF_STOCK', 'DISCONTINUED', name='hw_availability'), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('external_provider_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['hardware_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_switches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_switches_external_provider_id'), ['external_provider_id'], unique=False)

    op.create_table('power_supplies',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('wattage', sa.Integer(), nullable=True),
    sa.Column('form_factor', sa.String(length=20), nullable=True),
    sa.Column('efficiency_rating', sa.String(length=20), nullable=True),
    sa.Column('redundant', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability', sa.Enum('IN_STOCK', 'LIMITED', 'OUT_OF_STOCK', 'DISCONTINUED', name='hw_availability'), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('external_provider_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['hardware_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('power_supplies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_power_supplies_external_provider_id'), ['external_provider_id'], unique=False)

    op.create_table('raid_controllers',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('supported_raid_levels', sa.JSON(), nullable=True),
    sa.Column('cache_mb', sa.Integer(), nullable=True),
    sa.Column('interface', sa.String(length=50), nullable=True),
    sa.Column('port_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability', sa.Enum('IN_STOCK', 'LIMITED', 'OUT_OF_STOCK', 'DISCONTINUED', name='hw_availability'), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('external_provider_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['hardware_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raid_controllers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raid_controllers_external_provider_id'), ['external_provider_id'], unique=False)

    op.create_table('ram_modules',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=100), nullable=True),
    sa.Column('ddr_generation', sa.String(length=20), nullable=True),
    sa.Column('capacity_gb', sa.Integer(), nullable=True),
    sa.Column('speed_mhz', sa.Integer(), nullable=True),
    sa.Column('ecc', sa.Boolean(), nullable=True),
    sa.Column('registered', sa.Boolean(), nullable=True),
    sa.Column('buffered', sa.Boolean(), nullable=True),
    sa.Column('dimm_type', sa.String(length=20), nullable=True),
    sa.Column('rank', sa.String(length=20), nullable=True),
    sa.Column('voltage', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability', sa.Enum('IN_STOCK', 'LIMITED', 'OUT_OF_STOCK', 'DISCONTINUED', name='hw_availability'), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('external_provider_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['hardware_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ram_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ram_modules_external_provider_id'), ['external_provider_id'], unique=False)

    op.create_table('routers',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('routing_protocols', sa.JSON(), nullable=True),
    sa.Column('port_count', sa.Integer(), nullable=True),
    sa.Column('port_type', sa.String(length=50), nullable=True),
    sa.Column('port_speed_gbps', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('interface', sa.String(length=50), nullable=True),
    sa.Column('power_requirements', sa.String(length=100), nullable=True),
    sa.Column('rack_units', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability', sa.Enum('IN_STOCK', 'LIMITED', 'OUT_OF_STOCK', 'DISCONTINUED', name='hw_availability'), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('external_provider_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['hardware_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routers_external_provider_id'), ['external_provider_id'], unique=False)

    op.create_table('server_chassis',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('form_factor', sa.String(length=20), nullable=True),
    sa.Column('rack_units', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('drive_bays', sa.Integer(), nullable=True),
    sa.Column('max_gpu_count', sa.Integer(), nullable=True),
    sa.Column('max_psu_count', sa.Integer(), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability', sa.Enum('IN_STOCK', 'LIMITED', 'OUT_OF_STOCK', 'DISCONTINUED', name='hw_availability'), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('external_provider_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['hardware_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('server_chassis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_server_chassis_external_provider_id'), ['external_provider_id'], unique=False)

    op.create_table('storage_devices',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('storage_type', sa.Enum('HDD', 'SATA_SSD', 'NVME_SSD', name='storage_type'), nullable=False),
    sa.Column('capacity_gb', sa.Integer(), nullable=True),
    sa.Column('interface', sa.String(length=50), nullable=True),
    sa.Column('form_factor', sa.String(length=20), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('cache_mb', sa.Integer(), nullable=True),
    sa.Column('enterprise_rating', sa.String(length=50), nullable=True),
    sa.Column('workload_rating_tb_per_year', sa.Integer(), nullable=True),
    sa.Column('pcie_generation', sa.String(length=10), nullable=True),
    sa.Column('lane_count', sa.Integer(), nullable=True),
    sa.Column('read_speed_mbps', sa.Integer(), nullable=True),
    sa.Column('write_speed_mbps', sa.Integer(), nullable=True),
    sa.Column('random_read_iops', sa.Integer(), nullable=True),
    sa.Column('random_write_iops', sa.Integer(), nullable=True),
    sa.Column('endurance_dwpd', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tbw', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability', sa.Enum('IN_STOCK', 'LIMITED', 'OUT_OF_STOCK', 'DISCONTINUED', name='hw_availability'), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('external_provider_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['hardware_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storage_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storage_devices_external_provider_id'), ['external_provider_id'], unique=False)

    op.create_table('transceivers',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('transceiver_type', sa.Enum('SFP', 'SFP_PLUS', 'SFP28', 'QSFP', 'QSFP28', name='transceiver_type'), nullable=False),
    sa.Column('port_speed_gbps', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('connector_type', sa.String(length=50), nullable=True),
    sa.Column('wavelength_nm', sa.Integer(), nullable=True),
    sa.Column('max_distance_m', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability', sa.Enum('IN_STOCK', 'LIMITED', 'OUT_OF_STOCK', 'DISCONTINUED', name='hw_availability'), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('external_provider_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['hardware_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transceivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transceivers_external_provider_id'), ['external_provider_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transceivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transceivers_external_provider_id'))

    op.drop_table('transceivers')
    with op.batch_alter_table('storage_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storage_devices_external_provider_id'))

    op.drop_table('storage_devices')
    with op.batch_alter_table('server_chassis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_server_chassis_external_provider_id'))

    op.drop_table('server_chassis')
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routers_external_provider_id'))

    op.drop_table('routers')
    with op.batch_alter_table('ram_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ram_modules_external_provider_id'))

    op.drop_table('ram_modules')
    with op.batch_alter_table('raid_controllers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raid_controllers_external_provider_id'))

    op.drop_table('raid_controllers')
    with op.batch_alter_table('power_supplies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_power_supplies_external_provider_id'))

    op.drop_table('power_supplies')
    with op.batch_alter_table('network_switches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_switches_external_provider_id'))

    op.drop_table('network_switches')
    with op.batch_alter_table('network_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_cards_external_provider_id'))

    op.drop_table('network_cards')
    with op.batch_alter_table('gpus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gpus_external_provider_id'))

    op.drop_table('gpus')
    with op.batch_alter_table('firewalls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firewalls_external_provider_id'))

    op.drop_table('firewalls')
    with op.batch_alter_table('cpus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cpus_external_provider_id'))

    op.drop_table('cpus')
    with op.batch_alter_table('hardware_brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hardware_brands_slug'))

    op.drop_table('hardware_brands')
    # ### end Alembic commands ###
