"""Phase 4: custom server builder — configurations, compatibility and pricing rules

Revision ID: 9de4572a7fbf
Revises: 3f3202a992ba
Create Date: 2026-09-10 19:17:33.623061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de4572a7fbf'
down_revision = '3f3202a992ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compatibility_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.Enum('SOCKET_MATCH', 'MEMORY_GENERATION_MATCH', 'MAX_DRIVE_BAYS', 'MAX_GPU_COUNT', 'MAX_PSU_COUNT', 'PSU_WATTAGE_SUFFICIENT', 'DRIVE_INTERFACE_MATCH', name='compat_rule_type'), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('component_type', sa.Enum('CPU', 'RAM', 'STORAGE', 'GPU', 'NETWORK_CARD', 'RAID_CONTROLLER', 'POWER_SUPPLY', 'CHASSIS', name='pricing_component_type'), nullable=True),
    sa.Column('method', sa.Enum('PASS_THROUGH', 'MARKUP_PERCENT', 'MARKUP_AMOUNT', name='pricing_method'), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('datacenter_name', sa.String(length=150), nullable=True),
    sa.Column('additional_services', sa.JSON(), nullable=True),
    sa.Column('bandwidth_mbps', sa.Integer(), nullable=True),
    sa.Column('ip_addresses', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SAVED', 'ORDERED', name='configuration_status'), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('setup_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.Enum('CPU', 'RAM', 'STORAGE', 'GPU', 'NETWORK_CARD', 'RAID_CONTROLLER', 'POWER_SUPPLY', 'CHASSIS', name='config_component_type'), nullable=False),
    sa.Column('hardware_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['server_configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuration_components')
    op.drop_table('server_configurations')
    op.drop_table('pricing_rules')
    op.drop_table('compatibility_rules')
    # ### end Alembic commands ###
