"""Phase 7: Bring Your Own Equipment requests

Revision ID: a18743e43304
Revises: 4497ed5bae65
Create Date: 2026-09-10 19:43:03.608245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18743e43304'
down_revision = '4497ed5bae65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_networking', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('equipment_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_types_slug'), ['slug'], unique=True)

    op.create_table('customer_equipment_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_staff_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'TECHNICAL_REVIEW', 'INFORMATION_REQUIRED', 'APPROVED', 'REJECTED', 'INVOICE_ISSUED', 'SHIPPING_ARRANGED', 'LOCKED_FOR_SHIPMENT', 'IN_TRANSIT', 'RECEIVED', 'INSPECTION', 'DEPLOYMENT', 'COMPLETED', name='request_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('information_requested', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_number')
    )
    op.create_table('customer_equipment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('asset_number', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cpu_summary', sa.String(length=255), nullable=True),
    sa.Column('ram_summary', sa.String(length=255), nullable=True),
    sa.Column('storage_summary', sa.String(length=255), nullable=True),
    sa.Column('gpu_summary', sa.String(length=255), nullable=True),
    sa.Column('raid_summary', sa.String(length=255), nullable=True),
    sa.Column('psu_summary', sa.String(length=255), nullable=True),
    sa.Column('chassis_summary', sa.String(length=255), nullable=True),
    sa.Column('port_count', sa.Integer(), nullable=True),
    sa.Column('port_types', sa.String(length=255), nullable=True),
    sa.Column('port_speeds', sa.String(length=255), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('network_summary', sa.String(length=255), nullable=True),
    sa.Column('rack_mount', sa.Boolean(), nullable=True),
    sa.Column('u_height', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('power_requirements', sa.String(length=100), nullable=True),
    sa.Column('declared_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('replacement_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('insurance_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_types.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['customer_equipment_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='change_request_status'), nullable=False),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['customer_equipment_requests.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_equipment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.String(length=500), nullable=True),
    sa.Column('new_value', sa.String(length=500), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['customer_equipment_items.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['customer_equipment_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('attachment_type', sa.Enum('PHOTO_FRONT', 'PHOTO_REAR', 'PHOTO_SERIAL', 'SPECIFICATION_SHEET', 'PURCHASE_DOCUMENTATION', 'TECHNICAL_DOCUMENTATION', 'OTHER', name='attachment_type'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['customer_equipment_items.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment_attachments')
    op.drop_table('customer_equipment_history')
    op.drop_table('equipment_change_requests')
    op.drop_table('customer_equipment_items')
    op.drop_table('customer_equipment_requests')
    with op.batch_alter_table('equipment_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_types_slug'))

    op.drop_table('equipment_types')
    # ### end Alembic commands ###
