"""custom domains + ping endpoint

Revision ID: 08ac7ab62c92
Revises: 4842a118b198
Create Date: 2026-07-10 15:29:08.342041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ac7ab62c92'
down_revision = '4842a118b198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developer_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_domain', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('custom_domain_verified', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
        batch_op.add_column(sa.Column('custom_domain_checked_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developer_profiles', schema=None) as batch_op:
        batch_op.drop_column('custom_domain_checked_at')
        batch_op.drop_column('custom_domain_verified')
        batch_op.drop_column('custom_domain')

    # ### end Alembic commands ###
