"""developer marketplace

Revision ID: 3bb7bc785fef
Revises: e15d60d4fcc4
Create Date: 2026-07-10 18:24:38.367485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb7bc785fef'
down_revision = 'e15d60d4fcc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketplace_listed', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
        batch_op.add_column(sa.Column('purchase_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('purchase_url')
        batch_op.drop_column('marketplace_listed')

    # ### end Alembic commands ###
