"""version channels for modules and server attachments

Revision ID: 48e1aa1b21c8
Revises: 08ac7ab62c92
Create Date: 2026-07-10 18:05:37.737496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e1aa1b21c8'
down_revision = '08ac7ab62c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel', sa.String(length=20), server_default=sa.text("'stable'"), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_module_product_name'), type_='unique')
        batch_op.create_unique_constraint('uq_module_product_name_channel', ['product_id', 'name', 'channel'])

    with op.batch_alter_table('server_licenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel', sa.String(length=20), server_default=sa.text("'stable'"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server_licenses', schema=None) as batch_op:
        batch_op.drop_column('channel')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint('uq_module_product_name_channel', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_module_product_name'), ['product_id', 'name'])
        batch_op.drop_column('channel')

    # ### end Alembic commands ###
