"""admin action log

Revision ID: 7329aa400122
Revises: df8d6c53d0bb
Create Date: 2026-07-10 20:16:17.327306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7329aa400122'
down_revision = 'df8d6c53d0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_action_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_action_log_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_action_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_action_log_created_at'))

    op.drop_table('admin_action_log')
    # ### end Alembic commands ###
