"""developer nav redesign, workspace activity log

Revision ID: 7c1a6f918cc0
Revises: 3bb7bc785fef
Create Date: 2026-07-10 18:37:08.214309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1a6f918cc0'
down_revision = '3bb7bc785fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['developer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_activity_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_activity_log_developer_id'), ['developer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_activity_log_developer_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_activity_log_created_at'))

    op.drop_table('workspace_activity_log')
    # ### end Alembic commands ###
