"""email notification preference

Revision ID: df8d6c53d0bb
Revises: 7c1a6f918cc0
Create Date: 2026-07-10 18:54:31.410351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8d6c53d0bb'
down_revision = '7c1a6f918cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developer_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_notifications_enabled', sa.Boolean(), server_default=sa.text('(true)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developer_profiles', schema=None) as batch_op:
        batch_op.drop_column('email_notifications_enabled')

    # ### end Alembic commands ###
