"""remote configuration

Revision ID: e15d60d4fcc4
Revises: 48e1aa1b21c8
Create Date: 2026-07-10 18:11:40.213816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15d60d4fcc4'
down_revision = '48e1aa1b21c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remote_config', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('remote_config')

    # ### end Alembic commands ###
