"""add instance_commands + kiosk_process_status

Revision ID: 43263d930ff3
Revises: 5b6d0cfe37f3
Create Date: 2026-09-05 16:47:30.328082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43263d930ff3'
down_revision = '5b6d0cfe37f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('command_type', sa.String(length=16), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result_message', sa.Text(), nullable=True),
    sa.Column('acked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_instance_commands_instance_id_instances')),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_instance_commands_requested_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instance_commands')),
    sa.UniqueConstraint('public_id', name=op.f('uq_instance_commands_public_id'))
    )
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kiosk_process_status', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.drop_column('kiosk_process_status')

    op.drop_table('instance_commands')
    # ### end Alembic commands ###
