"""sync schema with named constraints

Revision ID: 5b6d0cfe37f3
Revises: e3c78283f90b
Create Date: 2026-09-05 00:03:30.790883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6d0cfe37f3'
down_revision = 'e3c78283f90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_companies_public_id'), ['public_id'])

    with op.batch_alter_table('company_invites', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_company_invites_token'), ['token'])

    with op.batch_alter_table('enrollment_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_enrollment_tokens_token'), ['token'])

    with op.batch_alter_table('remote_access_tokens', schema=None) as batch_op:
        # public_id/status/status_message were added to the RemoteAccessToken
        # model but a migration to actually create these columns was never
        # committed (see app/models.py) -- the alter_column/constraint calls
        # below assume they already exist, which is only true on a database
        # that had them hand-added outside Alembic. Adding them here first
        # so this migration works on a genuinely fresh database too.
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=16), nullable=False, server_default='pending'))
        batch_op.add_column(sa.Column('status_message', sa.Text(), nullable=True))

    # Backfill a unique public_id into any pre-existing rows before the
    # NOT NULL + UNIQUE constraints below are applied -- a single shared
    # server_default would violate the unique constraint the moment there's
    # more than one existing row.
    import uuid as _uuid
    conn = op.get_bind()
    rat = sa.table(
        'remote_access_tokens',
        sa.column('id', sa.Integer),
        sa.column('public_id', sa.String),
    )
    for row in conn.execute(sa.select(rat.c.id)).fetchall():
        conn.execute(
            rat.update().where(rat.c.id == row.id).values(public_id=str(_uuid.uuid4()))
        )

    with op.batch_alter_table('remote_access_tokens', schema=None) as batch_op:
        batch_op.alter_column('public_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.create_unique_constraint(batch_op.f('uq_remote_access_tokens_public_id'), ['public_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_remote_access_tokens_token'), ['token'])

    with op.batch_alter_table('staged_rollouts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_staged_rollouts_public_id'), ['public_id'])

    with op.batch_alter_table('update_deployments', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_update_deployments_public_id'), ['public_id'])

    with op.batch_alter_table('update_packages', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_update_packages_public_id'), ['public_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_update_packages_version'), ['version'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_public_id'), ['public_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_public_id'), type_='unique')

    with op.batch_alter_table('update_packages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_update_packages_version'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_update_packages_public_id'), type_='unique')

    with op.batch_alter_table('update_deployments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_update_deployments_public_id'), type_='unique')

    with op.batch_alter_table('staged_rollouts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_staged_rollouts_public_id'), type_='unique')

    with op.batch_alter_table('remote_access_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_remote_access_tokens_token'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_remote_access_tokens_public_id'), type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('public_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        # Drop the columns this migration's upgrade() adds, so downgrade
        # actually restores the initial_schema shape instead of leaving
        # orphaned columns behind.
        batch_op.drop_column('status_message')
        batch_op.drop_column('status')
        batch_op.drop_column('public_id')

    with op.batch_alter_table('enrollment_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_enrollment_tokens_token'), type_='unique')

    with op.batch_alter_table('company_invites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_company_invites_token'), type_='unique')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_companies_public_id'), type_='unique')

    # ### end Alembic commands ###
